### ISSUE TITLE
extension complains about object.watch not being defined on latest basilisk

### ISSUE THREAD

**Issue by ThosRTanner** [hawkeye116477/S4E_Revived#2]
The addon seems to be more or less still working, but it produces a long message in the console log on startup

**Comment by hawkeye116477** [comment]
Strange, I didn't see that message. Make sure that you uninstalled/disabled not Revived version.

**Comment by ThosRTanner** [comment]
Hmm. it's stopped happening now. When it does happen again I'll get the stack trace for you
